# Membuat Spreadsheet Pelabelan untuk Anotator

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import pandas as pd

file_path = '/content/drive/MyDrive/SKRIPSI_NAVY/Dataset/Dataset_Persiapan/Dataset_Translated/hotel_reviews_translated.csv'
df = pd.read_csv(file_path)

print("Ukuran dataset:", df.shape)
df

Ukuran dataset: (7821, 13)

,id,review_text,review_rating,review_date,url,username,hotel_name,city,hotel_rating,region,language,detected_language,review_text_translated
0,1,Pertama kali disini super kagum sama interior ...,5,2025-09-13,https://www.tripadvisor.com/ShowUserReviews-g2...,Deby A,Hotel Majapahit Surabaya - MGallery Collection,Surabaya,4.7,Surabaya,id,id,Pertama kali disini super kagum sama interior ...
1,2,Pelayanan oke banget dibantu dengan resepsioni...,5,2025-09-13,https://www.tripadvisor.com/ShowUserReviews-g2...,Mobile26477862893,Hotel Majapahit Surabaya - MGallery Collection,Surabaya,4.7,Surabaya,id,id,Pelayanan oke banget dibantu dengan resepsioni...
2,3,Kolam renang dan gym nya sangat bagus dan yang...,5,2025-08-27,https://www.tripadvisor.com/ShowUserReviews-g2...,Farid P,Hotel Majapahit Surabaya - MGallery Collection,Surabaya,4.7,Surabaya,id,id,Kolam renang dan gym nya sangat bagus dan yang...
3,4,Kami Sekeluarga senang. Kamarnya bersih dan ny...,5,2025-08-27,https://www.tripadvisor.com/ShowUserReviews-g2...,Navigate56583167160,Hotel Majapahit Surabaya - MGallery Collection,Surabaya,4.7,Surabaya,id,id,Kami Sekeluarga senang. Kamarnya bersih dan ny...
4,5,Perbotan kamar seperti AC dan dispenser air mi...,1,2025-08-26,https://www.tripadvisor.com/ShowUserReviews-g2...,robin,Hotel Majapahit Surabaya - MGallery Collection,Surabaya,4.7,Surabaya,id,id,Perbotan kamar seperti AC dan dispenser air mi...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7816,7817,Cukup unik karena ada kamar mandi portable yg ...,3,2023-10-13,https://www.tripadvisor.com/ShowUserReviews-g6...,KartikaMarta,POP! Hotel Kuta Beach,Legian,3.7,Bali,id,id,Cukup unik karena ada kamar mandi portable yg ...
7817,7818,"Small room with expensive price, doest have sl...",2,2023-10-03,https://www.tripadvisor.com/ShowUserReviews-g6...,thesweetzprincezz,POP! Hotel Kuta Beach,Legian,3.7,Bali,en,en,"Kamar kecil dengan harga mahal, tidak ada sand..."
7818,7819,Very poor service experience. The staff were u...,3,2023-09-10,https://www.tripadvisor.com/ShowUserReviews-g6...,afriscoa,POP! Hotel Kuta Beach,Legian,3.7,Bali,en,en,Pengalaman pelayanan yang sangat buruk. Stafny...
7819,7820,"Plus : pelayanan bagus, karyawan & staff ramah...",3,2023-09-09,https://www.tripadvisor.com/ShowUserReviews-g6...,Indi H,POP! Hotel Kuta Beach,Legian,3.7,Bali,id,id,"Plus : pelayanan bagus, karyawan & staff ramah..."
7820,7821,lokasi hotel ini ada di dalam gang kecil yang ...,3,2023-09-06,https://www.tripadvisor.com/ShowUserReviews-g6...,James W,POP! Hotel Kuta Beach,Legian,3.7,Bali,id,id,lokasi hotel ini ada di dalam gang kecil yang ...

In [3]:
# Menentukan Kolom untuk anotasi/pelabelan (id, review_text_translated, review_text)
annotation_df = df[['id', 'review_text', 'review_text_translated']].copy()
annotation_df['Room'] = ''
annotation_df['Hotel'] = ''
annotation_df['Location'] = ''
annotation_df['Service'] = ''

annotation_df

,id,review_text,review_text_translated,Room,Hotel,Location,Service
0,1,Pertama kali disini super kagum sama interior ...,Pertama kali disini super kagum sama interior ...,,,,
1,2,Pelayanan oke banget dibantu dengan resepsioni...,Pelayanan oke banget dibantu dengan resepsioni...,,,,
2,3,Kolam renang dan gym nya sangat bagus dan yang...,Kolam renang dan gym nya sangat bagus dan yang...,,,,
3,4,Kami Sekeluarga senang. Kamarnya bersih dan ny...,Kami Sekeluarga senang. Kamarnya bersih dan ny...,,,,
4,5,Perbotan kamar seperti AC dan dispenser air mi...,Perbotan kamar seperti AC dan dispenser air mi...,,,,
...,...,...,...,...,...,...,...
7816,7817,Cukup unik karena ada kamar mandi portable yg ...,Cukup unik karena ada kamar mandi portable yg ...,,,,
7817,7818,"Small room with expensive price, doest have sl...","Kamar kecil dengan harga mahal, tidak ada sand...",,,,
7818,7819,Very poor service experience. The staff were u...,Pengalaman pelayanan yang sangat buruk. Stafny...,,,,
7819,7820,"Plus : pelayanan bagus, karyawan & staff ramah...","Plus : pelayanan bagus, karyawan & staff ramah...",,,,
7820,7821,lokasi hotel ini ada di dalam gang kecil yang ...,lokasi hotel ini ada di dalam gang kecil yang ...,,,,

In [4]:
!pip install openpyxl

Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)

In [5]:
from openpyxl import load_workbook
from openpyxl.worksheet.datavalidation import DataValidation

base_path = '/content/drive/MyDrive/SKRIPSI_NAVY/Dataset/Dataset_Persiapan/Dataset_Pelabelan/RAW/Pelabelan_Annotator_1.xlsx'
second_path = '/content/drive/MyDrive/SKRIPSI_NAVY/Dataset/Dataset_Persiapan/Dataset_Pelabelan/Pelabelan_Annotator_1.xlsx'

# Simpan file
annotation_df.to_excel(base_path, index=False)

# Load kembali untuk tambah dropdown
wb = load_workbook(base_path)
ws = wb.active

# Buat dropdown validation
dv = DataValidation(
    type="list",
    formula1='"None,Positive,Negative"',
    allow_blank=True
)

# Tambahkan dropdown ke worksheet
ws.add_data_validation(dv)

# Tentukan range kolom aspek (kolom D sampai G)
max_row = ws.max_row
dv.add(f'D2:D{max_row}')  # Aspek Room
dv.add(f'E2:E{max_row}')  # Aspek Hotel
dv.add(f'F2:F{max_row}')  # Aspek Location
dv.add(f'G2:G{max_row}')  # Aspek Service

# Simpan ke lokasi pertama
wb.save(base_path)
print(f"File annotator_1.xlsx berhasil dibuat di {base_path}!")

# Simpan ke lokasi kedua
wb.save(second_path)
print(f"File annotator_1.xlsx berhasil disimpan juga di {second_path}!")

File annotator_1.xlsx berhasil dibuat di /content/drive/MyDrive/SKRIPSI_NAVY/Dataset/Dataset_Persiapan/Dataset_Pelabelan/RAW/Pelabelan_Annotator_1.xlsx!
File annotator_1.xlsx berhasil disimpan juga di /content/drive/MyDrive/SKRIPSI_NAVY/Dataset/Dataset_Persiapan/Dataset_Pelabelan/Pelabelan_Annotator_1.xlsx!

In [6]:
# File pelabelan untuk anotator 2 dan 3
for i in range(2, 4):
    raw_path = f'/content/drive/MyDrive/SKRIPSI_NAVY/Dataset/Dataset_Persiapan/Dataset_Pelabelan/RAW/Pelabelan_Annotator_{i}.xlsx'
    general_path = f'/content/drive/MyDrive/SKRIPSI_NAVY/Dataset/Dataset_Persiapan/Dataset_Pelabelan/Pelabelan_Annotator_{i}.xlsx'

    # Simpan file
    annotation_df.to_excel(raw_path, index=False)

    # Load kembali untuk menambahkan dropdown
    wb = load_workbook(raw_path)
    ws = wb.active

    dv = DataValidation(
        type="list",
        formula1='"None,Positive,Negative"',
        allow_blank=True
    )

    ws.add_data_validation(dv)

    max_row = ws.max_row
    dv.add(f'D2:D{max_row}')
    dv.add(f'E2:E{max_row}')
    dv.add(f'F2:F{max_row}')
    dv.add(f'G2:G{max_row}')

    # Simpan kembali (setelah penambahan dropdown)
    wb.save(raw_path)
    print(f"File annotator_{i}.xlsx berhasil dibuat di {raw_path}!")

    # Simpan ke path lain
    wb.save(general_path)
    print(f"File annotator_{i}.xlsx berhasil disimpan juga di {general_path}!")

print("Semua file anotator berhasil dibuat!")

File annotator_2.xlsx berhasil dibuat di /content/drive/MyDrive/SKRIPSI_NAVY/Dataset/Dataset_Persiapan/Dataset_Pelabelan/RAW/Pelabelan_Annotator_2.xlsx!
File annotator_2.xlsx berhasil disimpan juga di /content/drive/MyDrive/SKRIPSI_NAVY/Dataset/Dataset_Persiapan/Dataset_Pelabelan/Pelabelan_Annotator_2.xlsx!
File annotator_3.xlsx berhasil dibuat di /content/drive/MyDrive/SKRIPSI_NAVY/Dataset/Dataset_Persiapan/Dataset_Pelabelan/RAW/Pelabelan_Annotator_3.xlsx!
File annotator_3.xlsx berhasil disimpan juga di /content/drive/MyDrive/SKRIPSI_NAVY/Dataset/Dataset_Persiapan/Dataset_Pelabelan/Pelabelan_Annotator_3.xlsx!
Semua file anotator berhasil dibuat!